version: '3.7'
services:
    app:
        build:
            context: src
            dockerfile: ../Dockerfile
        image: escaperoombooking
        container_name: escaperoombooking
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: escaperoombooking
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        environment:
            MYSQL_DATABASE: escaperoombooking
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network

    webserver:
        image: nginx:mainline-alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./src:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
